# Generated by Django 2.2.24 on 2021-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_auto_20210702_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='has_highlights',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='historicalcourseoverview',
            name='has_highlights',
            field=models.NullBooleanField(default=None),
        ),
    ]
