# Generated by Django 2.2.24 on 2021-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_home_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableprogresspagestackedconfig',
            name='enabled',
            field=models.BooleanField(default=None, null=True, verbose_name='Enabled'),
        ),
    ]
