# Generated by Django 2.2.24 on 2021-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_duration_limits', '0008_auto_20190313_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedurationlimitconfig',
            name='enabled',
            field=models.NullBooleanField(default=None, verbose_name='Enabled'),
        ),
    ]
