# Generated by Django 2.2.24 on 2021-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_gating', '0008_auto_20190313_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttypegatingconfig',
            name='enabled',
            field=models.NullBooleanField(default=None, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='contenttypegatingconfig',
            name='studio_override_enabled',
            field=models.BooleanField(blank=True, default=None, help_text='Allow Feature Based Enrollment visibility to be overriden on a per-component basis in Studio.', null=True, verbose_name='Studio Override Enabled'),
        ),
    ]
