# Generated by Django 2.2.24 on 2021-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_gating', '0008_auto_20190313_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttypegatingconfig',
            name='enabled',
            field=models.BooleanField(default=None, null=True, verbose_name='Enabled'),
        ),
    ]
