# Generated by Django 2.2.24 on 2021-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20191022_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpercentageconfig',
            name='enabled',
            field=models.NullBooleanField(default=None, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='discountrestrictionconfig',
            name='enabled',
            field=models.NullBooleanField(default=None, verbose_name='Enabled'),
        ),
    ]
